# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Adrien Veillault - CV
email: veillault.adrien@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Adrien Veillault, développeur web. Agé de 21 ans, je suis passionné par les divers domaines du multimédia. Je suis quelqu'un de curieux, de travailleur et qui n'abbandonne pas facilement.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
location: "Allier, France"
yourname: "Adrien Veillault"
facebook: https://www.facebook.com/profile.php?id=100008751768052
linkedin: https://www.linkedin.com/in/adrien-veillault-8aa083130/?lipi=urn%3Ali%3Apage%3Ad_flagship3_people%3ByO5spTwdTni2RpwJVTvtUA%3D%3D&licu=urn%3Ali%3Acontrol%3Ad_flagship3_people-nav.settings_view_profile

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
